### ISSUE TITLE
Export encrypted data to file

### ISSUE THREAD

**Issue by germdove** [Authenticator-Extension/Authenticator#104]
Sorry if I'm a little behind, but I just updated Authenticator to the new layout and noticed that we no longer have the ability to create a backup with encrypted secrets. We used to have that ability, and encrypted backups can still be imported.

Can we get the ability to export encrypted secrets again?

**Comment by LeonardoCiaccio** [comment]
I share this project used to manage information locally.
Lightweight and performing, it has features like automatic data encryption [LocalDB](https://github.com/LeonardoCiaccio/LocalDB)

**Comment by mymindstorm** [comment]
@LeonardoCiaccio I don't think we would be able to use this since we currently use the [sync](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/storage/sync) storage space, which this doesn't seem to be compatible with your library. We only encrypt one key per entry so if we did use it we'd probably have to change a lot of small bits that would want access to the data even if it had a locked db. 

Really, the only thing blocking this request is building decryption support into the file upload screen which shouldn't be too painful.

**Comment by LeonardoCiaccio** [comment]
something like this?

```
var 
	 pass = prompt( "PASSWORD ?" ) || "" // <-- session password, load onetime in background

	,_enc = function( decrypted ){

		// ENCRYPT with session password

	}

	,_dec = function( encrypted ){

		// DECRYPT with session password

	}
;

chrome.storage.sync.set( { key : _enc( value ) }, function(){

   console.log( "Value is encrypted and set to " + value );

} );

chrome.storage.sync.get( [ "key" ], function( result ){

   console.log( "Value decrypted currently is " + _dec( result.key ) );

} );
```

**Comment by mymindstorm** [comment]
@LeonardoCiaccio that's pretty much what we already do. These are some of the parts that do decryption:
https://github.com/Authenticator-Extension/Authenticator/blob/4819fecfb3f948afe93748da9509854f54ce3044/src/models/storage.ts#L68-L85

https://github.com/Authenticator-Extension/Authenticator/blob/4819fecfb3f948afe93748da9509854f54ce3044/src/models/encryption.ts#L18-L53
