### ISSUE TITLE
Additional security

### ISSUE THREAD

**Issue by MrKornienko** [Authenticator-Extension/Authenticator#129]
Hello, You have an terrific app, but it would be even safer if You added a password feature EVERY time user access one-time codes.
This is not convenient, but will protect against viruses RMS / RAT.
Please don't let hackers steal our funds.
Sincerely, Alexander.

**Comment by mymindstorm** [comment]
Hi Alexander,

Your password is only cached in memory while the browser is open, all you need to do  to clear the cache is to close the browser. It's hard to strike a good balance between security and convenience. This extension makes it a lot more convenient to access your 2FA codes at the cost of some security. If you have a high-value account such as a bank or exchange account the only way to be 100% sure it won't be compromised because an attacker got your 2FA codes is to _only_ use a phone app to login.

In regards to your suggestion, I don't think we can force all of our users to re-enter their passwords every time. What about adding a "Remember Password" button? We already have that translated too.

**Comment by mymindstorm** [comment]
I forgot to mention that if you click the lock button in the top left it will re-lock the extension.

**Comment by MrKornienko** [comment]
Hello, the lock button became serviceable I have only after reinstalling the application, and this is really what I wanted. But I agree with You about using the phone, because with the help of the virus can know out any password.
Thank you for Your support and good luck.
