### ISSUE TITLE
Discussion about giving user the last chance to save backup when they uninstall the extension

### ISSUE THREAD

**Issue by Sneezry** [Authenticator-Extension/Authenticator#159]
It seems we cannot listen self-uninstall event, and what we can do is very limited.

There's a method that allows to open a URL when the extension is uninstalled. However, we still have two problems to use that method to help user download backup in the last minute:

1. The URL is in max length of 255. It is too short to pass backup data.
2. The URL must start with http: or https:, which means we must pass the backup data to a remote server, it doesn't make sense.

The method doc is here: https://developer.chrome.com/extensions/management#event-onUninstalled

**Comment by mymindstorm** [comment]
I think you meant this:
https://developer.chrome.com/extensions/runtime#method-setUninstallURL
https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/runtime/setUninstallURL
I don't think you'd be able to act on onUninstalled since Authenticator would likely be unloaded by then.


They probably don't let you do anything pre-uninstall since malicious extensions would abuse an event like that. 

1. Even if we could pass backup data via URL, wouldn't it be stored in user's browsing history?
2. Sending data to a backup server would be much more trouble than it's worth. In addition to maintaining a server and protecting it from attacks we would have to deal with complying to legal requirements like GDPR.

The most we can reasonably do with this is remind the user to check if they have a backup on  uninstall, which would be pointless on Chrome since the data would already be gone.

**Comment by Sneezry** [comment]
I agree. Then let's just close this issue.
