### ISSUE TITLE
Edge storage.sync.set broken

### ISSUE THREAD

**Issue by mymindstorm** [Authenticator-Extension/Authenticator#181]
```
Error: Could not complete the operation due to error 8e5e05e2.
```

The error:
- Is completely undocumented
- Only appears when packaged as an appx

I thought this was only happening because something wasn't provisioned for us on MSFT's side, guess I was wrong.

https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/18493567/

**Comment by mymindstorm** [comment]
Publishing a version that is on `edge-tempfix` that uses the local storage space for now.

**Comment by ericlaw1979** [comment]
This is a bug in Edge, where if the extension's "identity" is over 64 characters, storage is rejected due to exceeding the width of a database field. The identity is the combination of the publisher name, the AppX's Identity Name field, and a random hash.

**Comment by mymindstorm** [comment]
@ericlaw1979 are you talking about the package family name? The partner center says it's `2184mymindstorm.AuthenticatorExtension_80wqcq7zn3av4`, which is 52 characters long.

There really isn't much I can do about this since the partner dashboard forces me to use the ID it generates (and since it's already published it can't change). With Microsoft deprecating EdgeHTML hopefully most of the issues I found won't be coming back.

**Comment by ericlaw1979** [comment]
@mymindstorm: Thanks. I mostly left a note here because your issue is one of the top hits for this error message.

The "Extension ID" is "EdgeExtension_" + the package family name; the prefix adds 14 characters which pushes your extension's ID out to 66 characters, just over the limit. Unfortunately, there's no workaround short of re-releasing the extension with a shorter name.

I've reached out to the documentation team to ask them to document this bug, and to the partner onboarding team to help them reject any proposed listing with an ID that exceeds the limit.

You're correct in noting that the Chromium-based Edge will not suffer from this problem, but the old EdgeHTML-based version of Edge will be with us for quite some time.

**Comment by mymindstorm** [comment]
Closing as edge is being replaced with chromium Edge.
