### ISSUE TITLE
Privacy Policy words

### ISSUE THREAD

**Issue by Sneezry** [Authenticator-Extension/Authenticator#186]
It is incorrect to say 

> Authenticator may **collect** your account name, secret key ...

We never collect these data. The extension runs locally, and user data is never sent to us.

Privacy Policy has legal utility, we must regard it rigorously.

I personally strongly suggest to remove the Privacy Policy. Nether of us is a lawyer.

**Comment by mymindstorm** [comment]
Didn't know those were legally enforcable. It's required by Microsoft store policy. I'll just take it down, and if we get removed so be it.

**Comment by mymindstorm** [comment]
> f. Privacy Policy. You must maintain a privacy policy if (1) your App accesses, collects or transmits any Personal Information to you or a third party

Collects doesn't seem to imply transmitting data. It could be changed to "stores" for better clarification. I've looked through some other store listings and some haven't been forced to add a policy while others either have a full policy or don't take it too seriously.

The first thing I'm going to do if they deny the updated listing is contest it. If that fails we can either take down the listing or disable all sync and 3rd party backup on Edge (it's already like that due to EdgeHTML bugs & unimplemented features anyway) and just use a boilerplate policy for Edge only.

**Comment by Sneezry** [comment]
Then we can reference Edge and Dropbox privacy policy for sync.

**Comment by mymindstorm** [comment]
I'm not exactly sure if that's allowed and / or the proper way to word a clause like that to make it compliant. I don't think I can get out of making one so I'll just have it always use the local storage space (#181) and hide the Dropbox menu option for now ([identity isn't supported anyway](https://docs.microsoft.com/en-us/microsoft-edge/extensions/api-support/extension-api-roadmap)). That will keep anything from being complicated.

**Comment by mymindstorm** [comment]
I made a draft at [Edge Privacy Policy](https://github.com/Authenticator-Extension/Authenticator/wiki/Edge-Privacy-Policy).

**Comment by Sneezry** [comment]
I still concern the word collect. If we have any reference about the word, the policy looks good.
