### ISSUE TITLE
Token revoked i18n message doesn't show correctly in Chrome

### ISSUE THREAD

**Issue by Sneezry** [Authenticator-Extension/Authenticator#251]
This issue happens when sign in Google Drive in Chrome.

![snipaste20181203_135040](https://user-images.githubusercontent.com/1621293/49355445-936a1b80-f702-11e8-8e7b-f3f248847bfe.png)

**Comment by mymindstorm** [comment]
This is mostly because the client ID that is used by default is limited to production use, you need to make test credentials and change the client id in chrome-manifest.json.

There is a string substitution feature built into `i18n.getMessage` that I was unaware of that uses the `$` symbol. Likely because of the implementation of this feature Chrome decides to remove the preceding `${`, causing the regex to miss the substitution.

PR with fixes at #252
