### ISSUE TITLE
Change official website domain

### ISSUE THREAD

**Issue by Sneezry** [Authenticator-Extension/Authenticator#261]
As authenticator.cc has been blacklisted in multiple scanners, I doubt we have bought a dirty domain.

I have registered a new clean domain to use as our official domain. The new domain is authenticator-extension.org, and will be applied to web store and GitHub org in the next few days.

**Comment by mymindstorm** [comment]
Pretty sure the reason we are being auto-blacklisted is due to the `<meta>` redirect often being used by hackers after taking over sites. Since we redirect at the root level and the only thing on the site this is likely setting off auto-blacklist triggers for the less advanced scanners. If we can't make it a 301 redirect due to restrictions, why don't we try testing a simple page on authenticator.cc that uses a button instead of `<meta>` and seeing if that makes the dumber AV scanners delist us. If nothing changes after a few weeks then we can assume the domain is dirty.

**Comment by Sneezry** [comment]
Okay, then I open a new task to design our website.

**Comment by mymindstorm** [comment]
Closing in favor of #262
