### ISSUE TITLE
Manage number in order in the list

### ISSUE THREAD

**Issue by firekod** [Authenticator-Extension/Authenticator#320]
I have hundreds of entries in the Authenticator.
I enter the data directly in the backup file (authenticator.txt), because it is inconvenient to work through the interface.

Please add the ability to specify the line number in the reserve file, for example:
otpauth://totp/site1.com?secret=AYDTEEBF4RAD72PG&index=1
otpauth://totp/site2.com?secret=BYDTEEBF4RAD72PG&index=2
otpauth://totp/site3.com?secret=CYDTEEBF4RAD72PG&index=3

**Comment by mymindstorm** [comment]
We won't ever allow that in the normal backup since we want that backup format to work with other applications ([see more](https://authenticator.cc/docs/en/otp-backup)), but you can create an encrypted backup and edit the `index` parameter. This is the format encrypted backups use: https://github.com/Authenticator-Extension/Authenticator/issues/185#issuecomment-410532399
