### ISSUE TITLE
the QR code scanning of paypal is not working.

### ISSUE THREAD

**Issue by ghostkill3r** [Authenticator-Extension/Authenticator#371]
i'm getting a "unrecognized QR code" message when i try to scan the paypal QR code, wile trying  to configure paypal for the 2factor login thing  :(

Windows 10 x64
 - Browser: Firefox and Edge
 - Browser Version: Firefox: (as of writing) 70.0a1 (2019-07-31) (64-bit) Nightly
                               Edge :  (as of writing) Version 77.0.233.0 (Official build) canary (64-bit)

**Comment by mymindstorm** [comment]
Can you try to scan the code and follow [these directions](https://authenticator.cc/docs/en/debug-info)?

You can still add the account using manual entry.

**Comment by ghostkill3r** [comment]
it's working now for whatever reason, and trust me i tried it more than once. :/
maybe it's working now because of a browser update?
i'm sorry that i was to quick about it, and opened a thread/issue.

i will close this now, and again I'm sorry.

**Comment by spacesynth** [comment]
Sort of thread necro, but then again I provide a workaround:
Yes the issue is real and it seems to be with PayPal.

1) If I scan the code with a different **offline** QR reader I got a 75 byte TOTP string.
2) Using an **offline** QR generator I got a working code working perfectly in the Authenticator.
3) The codes look completely different.

I suspect PayPal uses a QR library that doesn't check properly for the best mask pattern:
https://en.wikipedia.org/wiki/File:QR_Code_Mask_Patterns.svg

Using bad mask patterns creates noise in some readers, making it hard for the Authenticator extension.

However Aegis authenticator on Android (zxing java) can read PayPal codes just fine, but given how hard it can be to find a decent JS library (zxiing js) I guess there is not much we can do.

Unless the developer here wants to switch:
NPM: https://www.npmjs.com/package/@zxing/library
Demo: https://zxing-js.github.io/library/examples/qr-image/
Github: https://github.com/zxing-js/library

FLOSS ready MIT license.

**Comment by mymindstorm** [comment]
@vaporwave9 thank you for the heads up, we have added a fallback qr scanning library in case the primary fails. It will land in the next release, hopefully that will help with situations like this.

**Comment by spacesynth** [comment]
That was fast! Thank you too for the great support. I really am happy you liked the idea. Maybe check the results against each other. Most scan fast enough in the ranges of 150ms. Have a nice week!

Edit:
The reason why is, i could get it to scan with the old library, but the shared secret imported was a wrong string compared to Aegis.
