### ISSUE TITLE
Support format for i18n

### ISSUE THREAD

**Issue by Sneezry** [Authenticator-Extension/Authenticator#378]
We need support format for i18n to resolve some limit.

Example:

English: Locked after 5 minutes

Chinese: 于5分钟后锁定

If we only provide `Locked after` and `minutes` for translation, `之后锁定` for `Locked after`, `分钟` for `minutes`, it will become `之后锁定5分钟`, which means `Locked for 5 minutes later` in Chinese.

Instead, `Locked for {0} minutes` or something else should be used.

---

i18n placeholder example: https://developer.chrome.com/extensions/i18n#examples-getMessage

**Comment by mymindstorm** [comment]
I don't think that we can just use `{0}` since it needs to be substituted with an input box. See:

https://github.com/Authenticator-Extension/Authenticator/blob/9465158fb77c78121d025aa6127632b3398bc34b/src/components/Popup/PrefrencesPage.vue#L27-L39

What about changing the i18n string names and css like this `autolock` => `before_autolock_input` and `minutes` => `after_autolock_input`?

Also `Locked after` is actually present tense (`Lock after`), though I doubt that changes the structure of the sentence that much.

**Comment by Sneezry** [comment]
See i18n placeholder example: https://developer.chrome.com/extensions/i18n#examples-getMessage

**Comment by mymindstorm** [comment]
That method only allows you the replace text, I didn't use that because I put an input element between the strings.

| Language | `autolock` / `before_autolock_input` | `minutes` / `after_autolock_input` | Image |
|----------|------------|-----------|-------|
|English| Lock after | minutes | ![Screenshot_20190821_200107](https://user-images.githubusercontent.com/27789806/63478246-ab2f2e80-c44e-11e9-9b37-e3e54d0a46da.png)  |
| Chinese | 于 | 分钟后锁定 |![Screenshot_20190821_202212](https://user-images.githubusercontent.com/27789806/63478913-65279a00-c451-11e9-8af0-fd290c94e118.png) |

If the way the input is arranged causes grammatical errors in Chinese, could you suggest a better way to arrange the input element? The way it is now is a bit odd, but I couldn't think of a good way to get the function of the setting across without the weird placement.

**Comment by Sneezry** [comment]
Got it.

**Comment by Kellywislon** [comment]
Lock after 5 minute
