### ISSUE TITLE
Option to not have to click "Show all entries"

### ISSUE THREAD

**Issue by chaddjohnson** [Authenticator-Extension/Authenticator#388]
**Describe the feature you want:**
Option to not have to click "Show all entries"

**Why do you want this feature in Authenticator?**
Almost every time I use Authenticator, I have to click "Show all entries."

**Comment by jhaar** [comment]
Same here. I don't have a huge number, but obviously large enough to trigger some "shrink-me" function. I have a particular TOTP I have to use several times per day and it's never the single entry that shows up - I always have to expand and then find. ie I already order them so the most used are listed first, but this "Show all entries" seems to only show the *last* TOTP token I added. BTW unrelated-but-related - it would be more useful for everyone that "Show all entries" shows the first  TOTP token - because end-users can re-sort their tokens to make use of that...?

Thanks!

**Comment by mymindstorm** [comment]
You can press "/" and it will clear the "Show all entries" and focus the search box. The filter tries to match the account name with the domain of the website you are on. E.g. if you name an entry "Google" it will filter whenever you are on "google.com". If you add `::sitename.com` to the end of an account name it will override the default filter. 

An entry should not show up on every site, what is the account name on the entry that you see this with?

**Comment by mymindstorm** [comment]
@Sneezry maybe we could track the number of times "Show all entries" is clicked and show an option to disable for certain accounts after 5 or so times in addition to an option to disable completely?

**Comment by Sneezry** [comment]
I think we can just add an option in settings to allow users to disable this feature

**Comment by jhaar** [comment]
I have always named the MFA based on my username - not the sitename. I work in Cybersecurity and have a range of accounts per site - and need TOTP for each of them, hence the naming by username not sitename. I didn't know about the "::site" trick - I will have to remember that :-)

**Comment by Sneezry** [comment]
@jhaar you can set issuer name to sitename.

![Snipaste_2020-07-21_15-12-01](https://user-images.githubusercontent.com/1621293/88023986-924e6200-cb64-11ea-8701-bc86aa0d9c41.png)

The extension also tries to match issuer name with current site. In the above example, Authenticator will show this entry when I open GitHub, because the issuer name (GitHub) is in the site name (The world’s leading software development platform · GitHub) and the site domain (github.com).

If you add `::example.com` after the issuer name (it's issuer name, not account name, see https://github.com/Authenticator-Extension/Authenticator/blob/dev/src/store/Accounts.ts#L599), that entry will be shown when you visit example.com. `::example.com` won't show in popup page, but you will see it in edit mode.

I don't recommend to use `::example.com` in issuer name, this is a hidden feature, it's not public in our docs. This feature may be removed in future versions.

**Comment by Radik248** [comment]
Hello! I need a program that makes $. accidentally lying around?


<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Без
вирусов. www.avast.ru
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

вс, 19 июл. 2020 г. в 22:39, Jason Haar <notifications@github.com>:

**Comment by Sneezry** [comment]
Feature added with PR https://github.com/Authenticator-Extension/Authenticator/pull/523
