### ISSUE TITLE
error import from aegis

### ISSUE THREAD

**Issue by 3xploiton3** [Authenticator-Extension/Authenticator#546]
<Do not use this to ask about lost codes or accounts>
<More info here: https://authenticator.cc/docs/en/lost-codes>

**Describe the bug:** <Describe the issue with Authenticator> 
can't import json from aegis,

**Platform:** <This is required>
 - Browser: [Chrome]
 - Browser Version:  87.0.4280.66

![image](https://user-images.githubusercontent.com/19517680/99498981-ccacfc00-29aa-11eb-9f3b-c8ce134d28f2.png)

![image](https://user-images.githubusercontent.com/19517680/99498995-d20a4680-29aa-11eb-9afd-f10de990a4c0.png)

**Comment by Sneezry** [comment]
We don't support Aegis backup format. Instead, we support to import from QR image and otpauth urls.

Currently, Aegis only supports to import Standard Backup Format (see https://authenticator.cc/docs/en/otp-backup). You may ask them to support to export this standard format, so that we can support Aegis backup.
