### ISSUE TITLE
Rename the extension with Authenticator CC

### ISSUE THREAD

**Issue by Sneezry** [Authenticator-Extension/Authenticator#718]
The simple extension name is a history issue. I created this extension as a fun project with an unserious name when I was a college student.

I can't imagine there are so many people who choose this small extension as their must-use-everyday tool. Till now (2021-07-22), there are more than 1.77M people installed this extension.

Back to the days I started to write this extension, I tried to make the extension have a similar appearance with Google's official mobile app to avoid too much learning cost for users who move from their smart phones to browsers. Though most users can use this extension without any pain point, the similar UI and generic name is a double-edged sword. We never try to mislead people to think this extension has any relationship with Google company, but some people do think this is a Google official production which can sync data from the Google's mobile app.

Renaming is a hard decision, especially there are millions of people who have recognized the name we are currently using.

Because we use authenticator.cc as our official website, some medium uses Authenticator.cc to reference the extension. I think Authenticator CC is an acceptable name, when I search "Authenticator CC" in Google, authenticator.cc is the first item in the list. If we must give a meaning to CC, I think we can say it stands for **C**redential **C**odes.

@mymindstorm how do you think of the proposal?

**Comment by mymindstorm** [comment]
Sorry about not getting back to you on this sooner.

I agree with you on needing to change the name, especially after looking at our search console data:

<table>
<tr>
	<td> <img src="https://user-images.githubusercontent.com/27789806/135534635-fe55b500-7a70-48dc-99d8-45060e60c174.png"/></td>
	<td> <img src="https://user-images.githubusercontent.com/27789806/135534705-ae301a98-260c-4e32-8ad7-e7529ababba5.png" </td>
</table>

Similar apps names usually share the same "\<company name\> Authenticator" format which we should take advantage of. Users will understand what the extension is more easily when keeping that format.

Regarding the specific suggestion, I don't think it escapes the problems that we are facing. We need to have something that ensures clarity over which "Authenticator" the extension is. I don't think that appending "CC" will solve that problem because it's fairly ambiguous.

We don't need to worry about search position as long as we keep the "Authenticator" part of the name intact, since our search impressions (to authenticator.cc) are mostly driven by that term as shown from the search console data. All we really need to do is pick an original (i.e. with little search presence already) proper noun to serve as a name and add "Authenticator" to it. Unfortunately, I don't have many ideas... Something that evokes the idea of defense/protected enclave?

Also, we need to have some redundancy in publishing access due to the large userbase in case one of us is unable to continue maintaining the extension. I am not suggesting any change to how we currently manage releases, just that we should have that access in place in the event that it is needed.

**Comment by mymindstorm** [comment]
We should also reconsider the use of "for Google Authenticator" on the Chrome promo tile. 

![Screenshot from 2021-10-23 18-53-50](https://user-images.githubusercontent.com/27789806/138574804-e8cb5602-1aa2-45ad-ae42-56b17741dfb2.png)
